---
- hosts: dev
  become: True
  tasks:
    
    - name: Start the container
      docker_container:
        name: hariapp
        image: "kammana/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8085:8085
