- hosts: docker-host
  become: true
  gather_facts: yes
  tasks:
    - name: Run docker run command to deploy java app on a container
      ansible.builtin.shell: sudo docker run -d -p 8085:8085 "shubhradeepghosh23/test-app:{{image_tag}}"
      register: result

    - ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"